spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/inventory?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  cloud:
    stream:
      bindings:
        inventory-out-0:
          destination: inventory
          content-type: application/json
      kafka:
        bindings:
          inventory-out-0:
            producer:
              configuration:
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
        binder:
          brokers: localhost:9094